/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.54
 * Generated at: 2021-11-12 09:51:17 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class Welcome_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"ISO-8859-1\">\r\n");
      out.write("<title>TE | Home</title>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"./bootstrap-4.6.1-dist/css/bootstrap.min.css\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("  <nav class=\"navbar navbar-dark bg-warning\">\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <a class=\"navbar-brand\" href=\"./Welcome.jsp\">\r\n");
      out.write("                <img src=\"te.jpeg\" alt=\"\" width=\"180\" height=\"50\">&emsp;&emsp;&emsp;\r\n");
      out.write("                <a href=\"./Welcome.jsp\" class=\"btn btn-dark \">Home</a>\r\n");
      out.write("            </a>\r\n");
      out.write("        </div>\r\n");
      out.write("    </nav>\r\n");
      out.write("    <div class=\"card text-center\">\r\n");
      out.write("        <div class=\"card-header\">\r\n");
      out.write("            <ul class=\"nav nav-pills card-header-pills\">\r\n");
      out.write("                <li class=\"nav-item\">\r\n");
      out.write("                </li>\r\n");
      out.write("            </ul>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"card-body badge-warning\">\r\n");
      out.write("            <h3 class=\"card-title badge-danger\">Welcome to TechnoElevate</h3><br>\r\n");
      out.write("            <p class=\"card-text\">Technoelevate has experience of delivering IT solutions using a combination of design,\r\n");
      out.write("                development and deployment in a wide variety of verticals and having worked in both Onshore, Offshore\r\n");
      out.write("                and a mixed delivery model.</p><br>\r\n");
      out.write("            <a href=\"./Login.jsp\" class=\"btn btn-dark\">Login</a>\r\n");
      out.write("            <a href=\"./Register.jsp\" class=\"btn btn-dark\">Register</a>\r\n");
      out.write("        </div>\r\n");
      out.write("        <br>\r\n");
      out.write("        <h4 class=\" text-md-left badge-secondary\">WHO WE ARE :- </h4>\r\n");
      out.write("       <div class=\"badge-info border-dark\">\r\n");
      out.write("        <p class=\" text-left\">Technoelevate is a fast-growing IT development unit who is providing a wide range of high quality development\r\n");
      out.write("            services for more than 2500+ people organizations, with presence across 6 countries â USA, UK, Netherlands,\r\n");
      out.write("            Ireland, Poland and Global Delivery Center in India.</p>\r\n");
      out.write("        <p class=\" text-left\">Over a decade that's 13 years, we have established an excellent track record of delivering the products and\r\n");
      out.write("            services to Fortune 100+ clients in diverse Industry domains such as Telecom, BFSI, Retail, E-commerce,\r\n");
      out.write("            Media & Entertainment, Technology. Our technical delivery group has vast experience of delivering cutting\r\n");
      out.write("            edge solutions for platforms such as Mobile, IoT, Cloud, Analytics, Blockchain and AI.</p>\r\n");
      out.write("        <p class=\" text-left\">\r\n");
      out.write("            We also have been an integral part of the IT skills development ecosystem and worked with Government\r\n");
      out.write("            projects, Universities and Corporates to bridge the IT skills gap. We have transformed over 600,000\r\n");
      out.write("            graduates into \"IT Ready\" job seekers and are proud to say that over 70% of them have landed on well known\r\n");
      out.write("            IT MNCs and also within Technoelevate.\r\n");
      out.write("        </p>\r\n");
      out.write("        <p class=\" text-left\">\r\n");
      out.write("            We were well known for our focus on product delivery and deployment, we draw from our experience over 13\r\n");
      out.write("            years of having worked with Industry Leaders across diverse industries. This has enabled us to differentiate\r\n");
      out.write("            ourselves from providing traditional technology which has helped us to be recognize as a preferred workplace\r\n");
      out.write("            for those who are passionate about technology.\r\n");
      out.write("        </p>\r\n");
      out.write("    </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <script src=\"./jquery.slim.min.js\"></script>\r\n");
      out.write("    <script src=\"./bootstrap-4.6.1-dist/js/bootstrap.min.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
